### ISSUE TITLE
duration parameter doesn't work as expected

### ISSUE THREAD

**Issue by doppelmarker** [ReggX/pydirectinput_rgx#6]
Methods like move(), moveTo() and moveRel() have duration param, which doesn't seem to work correctly. Whenever it is set to 0, then the cursor is moved immediately, but whenever I pass any value to it, it always moves in the same fast way. What is more, whenever the cursor is close to the edge of the screen, the duration parameter starts to be respected and the cursor just moves to the planned direction for the given amount of duration seconds.

Windows 10, tried Python 3.7 and 3.11

Please, tell me if I can provide you more info about my system, thanks

**Comment by ReggX** [comment]
Can you give examples of the distance and duration values used?

**Comment by doppelmarker** [comment]
This is the way I try to use it:

`import pydirectinput
pydirectinput.calibrate_real_sleep_minimum(verbose=True)


pydirectinput.move(500, 0, duration=10)`

The verbose output is:
`Calibrating real sleep minimum...
Real measurements: [4.4800000000000005e-05, 3.08e-05, 2.7400000000000002e-05, 2.0600000000000003e-05, 2.68e-05, 2.7700000000000002e-05, 2.64e-05, 2.15e-05, 2.5300000000000002e-05, 2.61e-05]
Rounding max measurement to next higher value in same order of magnitude: 5e-05
Changing MINIMUM_SLEEP_ACTUAL from 0.002 to 5e-05`

I get the same problem even using default sleep values without calibration

**Comment by ReggX** [comment]
Ah yes, I see the problem. If the distance is too short, then it won't be able slow down enough.

This can probably be fixed by adding artificial sleep steps in between micro movements.

**Comment by doppelmarker** [comment]
Fine, will handle my use case by moving for shorter steps and adding artificial sleeps

**Comment by ReggX** [comment]
Thanks to your comments, I decided to investigate the issue and rework how the movement system works.

It should be a lot more solid now and the duration should be a lot closer to the expected value.
