### ISSUE TITLE
User error or bug re: move (relative mouse movement)?

### ISSUE THREAD

**Issue by teddybear082** [ReggX/pydirectinput_rgx#7]
Hi thanks so much for your work updating pydirectinput and I was excited to find it on PyPi.

I submitted a PR to this project, wingman-ai, to implement pydirectinput-rgx (pyautogui is still used in the alternative for mac users of the project), and encountered unexpected behavior with relative mouse movement.  Wondering if this is user error or a bug.

You can see the most recent PR here: https://github.com/ShipBit/wingman-ai/pull/99/commits/3569bffecb0b0d1ed34a11e801e5f41069ec6aef

I was having an issue where using the move(x,y) or move(x,y,duration=[duration]) functions were not using relative movement. If, for example, the current mouse position was 900,600, and x,y was 0, 100, the cursor would move to 0,100 not 900,700.  I tested by running print statements of the current mouse position (position()), ensuring x, y were integers, and then printing the final mouse postion, and with 0,-100; 100,0; -100,0; 0,100 and each had the same issue when running move(x,y) or move(x,y,duration) with putting the cursor up at the top left corner of the screen with various offsets.  I also tried setting duration to 0.5, 1, and 2 and although I could see the cursor moving slower, it still went to the same place.

As you can see in the PR, I reverted by calculating a new absolute position manually and then using the moveTo function instead, and that works fine.

Is this a bug or user error? Thanks!

**Comment by ReggX** [comment]
Hi,

this is indeed a bug (Probably sneaked in during the 2.1 refactor). I'll look into uploading an updated version soon.

**Comment by ReggX** [comment]
Uploaded a new version to PyPI. Please see if that fixes your issue.

Also a small reminder: If you want to use real relative mouse movement, then you have to specifiy the `relative=True` argument when calling `moveTo`/`moveRel`. Otherwise it will fall back to calculating the target position and use absolute movement. This behavior is kept for compatibility to the original pydirectinput 1.0.4.

**Comment by teddybear082** [comment]
Wow thanks for the quick fix I will try it out as soon as I can! Appreciate it.

**Comment by teddybear082** [comment]
Just circling back to say thanks again, tried and worked great and implemented in the other project.
